# Site settings
title: Robosane Tech
email: robobenklein@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Robosane Tech is here to give you the latest news on Tech! We'll
  be posting the Weekly GNUs along with other interesting things.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://robosane.tk" # the base hostname & protocol for your site
twitter_username: Robosane
github_username:  Robosane

# Build settings
markdown: kramdown
